services:

  apache-php:
    image: customized-apache-httpd-plus-php:1.0
    hostname: apache-2.4-php-8.2-mcs8104-lab1
    container_name: apache-2.4-php-8.2-mcs8104-lab1
    restart: always
    ports:
      - 8002:80
    volumes:
      # To store the web-related files in a persistent volume (folder) in the host
      - ./container-volumes/apache/var-www-html:/var/www/html/
      # To store the PHP configuration file in the host
      - ./container-volumes/apache/etc-php/php.ini:/usr/local/etc/php/php.ini
    environment:
      PHP_DISPLAY_ERRORS: 1
      PHP_DISPLAY_STARTUP_ERRORS: 1
    command: >
      /bin/bash -c "
      echo 'display_errors = On' >> /usr/local/etc/php/php.ini &&
      echo 'display_startup_errors = On' >> /usr/local/etc/php/php.ini &&
      apache2-foreground
      "

  mysql:
    image: customized-mysql:1.0
    hostname: mysql-9.1.0-mcs8104-lab1
    container_name: mysql-9.1.0-mcs8104-lab1
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 5trathm0re
    volumes:
      # To store the server's configuration file in the host
      - mysql-config:/etc/mysql/
      # To store the server's data persistently in the host
      - mysql-data:/var/lib/mysql
      # To run the SQL scripts used to create the required databases
      - mysql-init:/docker-entrypoint-initdb.d/ # To run the SQL scripts used to create the required databases
    command: >
      /bin/bash -c "
      chmod 644 /etc/mysql/my.cnf &&
      exec docker-entrypoint.sh mysqld
      "

  mariadb:
    image: mariadb:11.6.2-noble
    hostname: mariadb-11.6.2-mcs8104-lab1
    container_name: mariadb-11.6.2-mcs8104-lab1
    restart: always
    ports:
      - 3308:3306
    environment:
      MARIADB_ROOT_PASSWORD: 5trathm0re
    volumes:
      # To store the server's configuration file in the host
      - ./container-volumes/mariadb/etc-mysql/my.cnf:/etc/mysql/my.cnf
      # To store the server's data persistently in the host
      - ./container-volumes/mariadb/var-lib-mysql:/var/lib/mysql
    command: >
      /bin/bash -c "
      chmod 644 /etc/mysql/my.cnf &&
      exec docker-entrypoint.sh mariadbd
      "

  postgres:
    image: postgres:17.2
    hostname: postgres-17.2-mcs8104-lab1
    container_name: postgres-17.2-mcs8104-lab1
    restart: always
    shm_size: 1g
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5trathm0re
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      # To store the server's configuration files (postgresql.conf and pg_hba.conf) in the host
      - ./container-volumes/postgresql/etc-postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./container-volumes/postgresql/etc-postgresql/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      # To store the server's data persistently in the host
      - ./container-volumes/postgresql/var-lib-postgresql-data:/var/lib/postgresql/data
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'

volumes:
  mysql-config:
    driver: local # The volume will be stored locally on the host machine
    driver_opts:
      type: none # Binds to the path specified in "device" instead of creating a new directory/file on the host
      o: bind # Confirms that Docker maps a directory/file on the host directly into the container
      device: ./container-volumes/mysql/etc-mysql/
  mysql-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./container-volumes/mysql/var-lib-mysql/
  mysql-init:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./container-volumes/mysql/init-scripts/